language: elixir
elixir:
  - '1.8.1'
otp_release:
  - '21.3'
services:
  - docker
cache:
  directories:
    - deps
    - _build/dev
    - _build/test
    - _build/integration
before_cache:
  - bash scripts/travis-uncache.sh
stages:
  - build
  - name: publish
    if: (branch == master || branch == travis-test) && type != pull_request
jobs:
  include:
    - stage: build
      name: static analysis
      script: bash scripts/travis-verify.sh
    - name: unit test
      script: mix test
    - name: pipeline
      script: bash scripts/travis-test.sh pipeline
    - name: providers
      script: bash scripts/travis-unit-test.sh providers
    - name: dead_letter
      script: bash scripts/travis-test.sh dead_letter
    - name: e2e
      script: bash scripts/travis-test.sh e2e force
    - name: discovery_api
      script: bash scripts/travis-test.sh discovery_api
    - name: tableau-wdc
      script: bash scripts/wdc-test.sh
    - name: andi
      script: bash scripts/travis-test.sh andi
    - name: flair
      script: bash scripts/travis-test.sh flair
    - name: forklift
      script: bash scripts/travis-test.sh forklift
    - name: valkyrie
      script: bash scripts/travis-test.sh valkyrie
    - name: reaper
      script: bash scripts/travis-test.sh reaper
    - name: estuary
      script: bash scripts/travis-test.sh estuary
    - name: discovery_streams
      script: bash scripts/travis-test.sh discovery_streams
    - name: odo
      script: bash scripts/travis-test.sh odo
    - stage: publish
      name: publish andi
      script: bash scripts/travis-publish.sh andi
    - name: publish reaper
      script: bash scripts/travis-publish.sh reaper
    - name: publish discovery_api
      script: bash scripts/travis-publish.sh discovery_api
    - name: publish estuary
      script: bash scripts/travis-publish.sh estuary
    - name: publish microservices
      script:
      - | 
        bash scripts/travis-publish.sh valkyrie
        bash scripts/travis-publish.sh forklift
        bash scripts/travis-publish.sh flair
        bash scripts/travis-publish.sh discovery_streams
        bash scripts/travis-publish.sh odo
    - name: release
      if: tag =~ /^(andi|reaper|valkyrie|forklift|flair|estuary|discovery_streams|odo|discovery_api)@\d{1,3}\.\d{1,3}\.\d{1,3}$/
      script: bash scripts/travis-publish.sh
branches:
  only:
  - travis-test
  - master
  - /(andi|reaper|valkyrie|forklift|flair|estuary|discovery_streams|odo|discovery_api)@\d{1,3}\.\d{1,3}\.\d{1,3}/
