language: elixir
elixir:
  - 1.8.1
opt_release:
  - 21.3
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.23.1
cache:
  directories:
    - deps
install:
  - bash scripts/travis-install.sh
script:
  - bash scripts/travis-build.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/travis-publish.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash scripts/travis-publish.sh
    on:
      tags: true
branches:
  only:
  - master
  - /(andi|forklift|flair):\d{1,3}\.\d{1,3}\.\d{1,3}/
