language: elixir
elixir:
  - '1.8.1'
otp_release:
  - '21.3'
services:
  - docker
cache:
  directories:
    - deps
    - _build/dev
    - _build/test
    - _build/integration
before_cache:
  - bash scripts/travis-uncache.sh
jobs:
  include:
    - stage: publish
      name: development
      script: bash scripts/travis-publish.sh
branches:
  only:
  - master
  - /(andi|reaper|valkyrie|forklift|flair|estuary|discovery_streams|odo)@\d{1,3}\.\d{1,3}\.\d{1,3}/
