language: elixir
elixir:
  - '1.8.1'
otp_release:
  - '21.3'
services:
  - docker
cache:
  directories:
    - deps
    - _build/dev
    - _build/test
    - _build/integration
before_cache:
  - bash scripts/travis-uncache.sh
jobs:
  include:
    - stage: build
      name: static analysis
      script: bash scripts/travis-verify.sh
    - name: unit test
      script: mix test
    - name: pipeline
      script: bash scripts/travis-test.sh pipeline
    - name: dead_letter
      script: bash scripts/travis-test.sh dead_letter
    - name: e2e
      script: bash scripts/travis-test.sh e2e
    - name: andi
      script: bash scripts/travis-test.sh andi
    - name: flair
      script: bash scripts/travis-test.sh flair
    - name: forklift
      script: bash scripts/travis-test.sh forklift
    - stage: publish
      name: development
      if: branch == master && type != pull_request
      script: bash scripts/travis-publish.sh
    - name: release
      if: tag =~ /^(andi|forklift|flair)@\d{1,3}\.\d{1,3}\.\d{1,3}$/
      script: bash scripts/travis-publish.sh
branches:
  only:
  - master
  - /(andi|forklift|flair)@\d{1,3}\.\d{1,3}\.\d{1,3}/
