version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 20s
      retries: 3
  ldap:
    image: osixia/openldap
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: --copy-service
    healthcheck:
      test: ["CMD-SHELL", "ldapsearch -x -H ldap://localhost -b dc=example,dc=org -D 'cn=admin,dc=example,dc=org' -w admin"]
      interval: 5s
      timeout: 20s
      retries: 3
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
    - zookeeper
    ports:
    - "9094:9094"
    environment:
    - "KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://${HOST_IP:-localhost}:9094"
    - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
    - "KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9094"
    - "KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE"
    - "KAFKA_CREATE_TOPICS=streaming-transformed:1:1,streaming-dead-letters:1:1,streaming-persisted:1:1"
    - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
    healthcheck:
      test: ["CMD-SHELL", "cat /opt/kafka/logs/server.log | grep \"Previous Leader Epoch was: -1\""]
      interval: 10s
      timeout: 20s
      retries: 3
  metastore:
    image: smartcitiesdata/metastore-testo:development
    container_name: metastore
    depends_on:
    - postgres
    ports:
    - "9083:9083"
    command: >
      /bin/bash -c "
        /opt/hive-metastore/bin/schematool -dbType postgres -validate || /opt/hive-metastore/bin/schematool -dbType postgres -initSchema;
        /opt/hive-metastore/bin/start-metastore"
  postgres:
    container_name: postgres
    logging:
      driver: none
    image: smartcitiesdata/postgres-testo:development
    ports:
    - "5432:5432"
  minio:
    container_name: minio
    image: smartcitiesdata/minio-testo:development
    ports:
    - "9000:9000"
  presto:
    container_name: presto
    depends_on:
    - metastore
    - minio
    image: smartcitiesdata/presto-testo:development
    ports:
    - "8081:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080/v1/info | grep -q '\"starting\":false'"]
      interval: 10s
      timeout: 30s
      retries: 10
  andi:
    container_name: andi
    image: smartcitiesdata/andi:development
    ports:
      - "8080:80"
    depends_on:
      - redis
      - ldap
    environment:
      - LDAP_HOST=ldap
      - LDAP_BASE=dc=example,dc=org
      - LDAP_USER=cn=admin
      - LDAP_ENV=local
      - LDAP_PASS=admin
      - REDIS_HOST=redis
  reaper:
    image: smartcitiesdata/reaper:tmptest
    container_name: reaper
    depends_on:
      - redis
      - kafka
      - vault
    environment:
      - REDIS_HOST=redis
      - KAFKA_BROKERS=kafka:9094
      - OUTPUT_TOPIC_PREFIX=raw
      - DLQ_TOPIC=streaming-dead-letters
      - DOWNLOAD_DIR=/tmp/
      - HOSTED_FILE_BUCKET=local-bucket
  valkyrie:
    container_name: valkyrie
    image: smartcitiesdata/valkyrie:development
    depends_on:
      - redis
      - kafka
    environment:
      - REDIS_HOST=redis
      - KAFKA_BROKERS=kafka:9094
      - INPUT_TOPIC_PREFIX=raw
      - OUTPUT_TOPIC_PREFIX=validated
      - DLQ_TOPIC=streaming-dead-letters
  voltron:
    container_name: voltron
    image: smartcitiesdata/voltron:development
    depends_on:
      - kafka
      - redis
    environment:
      - REDIS_HOST=redis
      - KAFKA_BROKERS=kafka:9094
      - INPUT_TOPIC_PREFIX=validated
      - OUTPUT_TOPIC_PREFIX=transformed
      - TO_TOPIC=streaming-transformed
  forklift:
    container_name: forklift
    image: smartcitiesdata/forklift:development
    depends_on:
      - kafka
      - redis
      - presto
    environment:
      - REDIS_HOST=redis
      - KAFKA_BROKERS=kafka:9094
      - DATA_TOPIC_PREFIX=transformed
      - OUTPUT_TOPIC=streaming-persisted
      - PRESTO_USER=forklift
      - PRESTO_URL=http://presto:8080
  streisand:
    container_name: streisand
    image: smartcitiesdata/streisand:development
    depends_on:
      - kafka
      - redis
    environment:
      - REDIS_HOST=redis
      - PIPELINE_KAFKA_BROKERS=kafka:9094
      - PUBLIC_KAFKA_BROKERS=kafka:9094
  flair:
    container_name: flair
    image: smartcitiesdata/flair:development
    depends_on:
      - kafka
      - redis
      - presto
    environment:
      - REDIS_HOST=redis
      - KAFKA_BROKERS=kafka:9094
      - DATA_TOPIC=streaming-persisted
      - DLQ_TOPIC=streaming-dead-letters
      - PRESTO_USER=flair
      - PRESTO_URL=http://presto:8080
  carpenter:
    container_name: carpenter
    image: smartcitiesdata/carpenter:development
    depends_on:
      - redis
      - presto
    environment:
      - REDIS_HOST=redis
      - PRESTO_URL=http://presto:8080
      - PRESTO_USER=carpenter
  discovery-api:
    container_name: discovery-api
    image: smartcitiesdata/discovery_api:development
    depends_on:
      - redis
      - presto
      - ldap
    environment:
      - LDAP_HOST=ldap
      - LDAP_BASE=dc=example,dc=org
      - LDAP_USER=cn=admin
      - LDAP_ENV=local
      - LDAP_PASS=admin
      - REDIS_HOST=redis
      - PRESTO_URL=http://presto:8080
      - ALLOWED_ORIGINS=*
    ports:
      - 8082:80
  discovery-streams:
    container_name: discovery-streams
    image: smartcitiesdata/discovery_streams:development
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9094
    ports:
      - 8087:4000
    restart: on-failure
  discovery_ui:
    container_name: discovery_ui
    image: smartcitiesdata/discovery_ui:development
    depends_on:
      - discovery-api
    environment:
      - API_HOST=http://localhost:8082
      - BASE_URL=http://localhost
    ports:
      - 8085:80
  genesis:
    container_name: genesis
    image: smartcitiesdata/genesis:development
    depends_on:
      - kafka
      - redis
    restart: on-failure
    environment:
      - REDIS_HOST=redis
      - PIPELINE_KAFKA_BROKERS=kafka:9094
      - PUBLIC_KAFKA_BROKERS=kafka:9094
      - TOPIC_PARTITIONS=1
      - TOPIC_REPLICATION_FACTOR=1
  data-generator:
    container_name: data-generator
    image: smartcitiesdata/data-generator:development
    depends_on:
      - redis
    ports:
      - 8083:80
    environment:
      - REDIS_HOST=redis
  vault:
    container_name: vault
    image: vault:1.1.2