name: E2E
env:
  NAME: e2e
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Verify Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 21.3
          elixir-version: 1.8.2
      - name: Get dependencies
        run: |
          bash scripts/gh-action-get-deps.sh
      - name: Run static checks
        run: |
          bash scripts/gh-action-static-checks.sh ${NAME}
      - name: Run integration tests
        run: |
          bash scripts/gh-action-integration-test.sh ${NAME}
