name: Pipeline
on:
  push:
    branches:
      - master
    paths:
    - 'apps/pipeline/**'
    - 'mix.lock'
  pull_request:
    branches:
      - master
    paths:
    - 'apps/pipeline/**'
    - 'mix.lock'

jobs:
  ci:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 21.3
          elixir-version: 1.8.2
      - name: Get dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run integration tests
        run: |
          bash scripts/gh-action-test.sh pipeline

