name: valkyrie
on:
  push:
    branches:
      - master
    paths:
    - 'apps/valkyrie/**'
    - 'mix.lock'
  pull_request:
    branches:
      - master
    paths:
    - 'apps/valkyrie/**'
    - 'mix.lock'
  workflow_dispatch:
    branches:
      - master

jobs:
  ci:
    name: Verify Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 21.3
          elixir-version: 1.8.2
      - name: Get dependencies
        run: |
          bash scripts/gh-action-get-deps.sh
      - name: Run static checks
        run: |
          bash scripts/gh-action-static-checks.sh ${GITHUB_WORKFLOW}
      - name: Run unit tests
        run: |
          bash scripts/gh-action-unit-test.sh ${GITHUB_WORKFLOW}
      - name: Run integration tests
        run: |
          bash scripts/gh-action-integration-test.sh ${GITHUB_WORKFLOW}
      - name: Publish development image
        run: |
          bash scripts/gh-action-publish.sh ${GITHUB_WORKFLOW}
        if: contains(['push', 'workflow_dispatch'], github.event_name)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
