name: version_checker
on: [pull_request_target]

jobs:
  check-apps-for-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Elixir
        uses: actions/setup-elixir@v1.2.0
        with:
          elixir-version: 1.9
          otp-version: 22.2
          runs-on: ubuntu-latest
      - name: Git Stuff
        id: git
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/* 
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Check App versions
        run: |
          export MESSAGE=$(bash scripts/gh-action-check-version.sh)
          echo ::set-output name=pr_message::${MESSAGE:-No app changes detected}
        id: differ
      - name: Comment PR
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ${{ steps.differ.outputs.pr_message }}
